name: Build LaTeX document
on: [push]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
      - name: Commit the PDF file and push to gh-pages branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update resume.pdf"
          branch: gh-pages
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
      - name: Release PDF file
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: resume.pdf
