name: Build LaTeX document
on: [push]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
      - name: Move generated resume.pdf to public folder
        run: |
          mkdir public
          mv resume.pdf public
      - name: Deploy public directory to the remote gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
      - name: Release PDF file
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: resume.pdf
